name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.8
    with:
      working_directory: './examples/Simple_SQL_Single_Database_with_Private_Endpoint/'
